requires 'CallBackery', '>=0.38.11';
requires 'Mojo::SQLite', '>= 3.006';
requires 'Email::MIME';
requires 'Email::Sender';
requires 'Email::Address';
requires 'Mojolicious::Plugin::OpenAPI';
requires 'Crypt::ScryptKDF';
requires 'YAML::XS';
requires 'SQL::Abstract::Pg';
requires 'JSON::Validator';
requires 'Carp::Always';
requires 'Time::Piece', '>= 1.3401';