requires 'Mojolicious';
requires 'Future::AsyncAwait';
requires 'EV';
requires 'CallBackery', '>=0.39.6';
requires 'Mojo::SQLite', '>= 3.006';
requires 'Email::MIME';
requires 'Email::Sender';
requires 'Email::Address';
requires 'Mojolicious::Plugin::OpenAPI';
requires 'Crypt::ScryptKDF';
requires 'YAML::XS';
requires 'SQL::Abstract::Pg';
requires 'JSON::Validator';
requires 'Carp::Always';
requires 'Time::Piece', '>= 1.3401';